- name: Connecting to F5 LTMs
  hosts: dc1f5ltm01
  connection: ssh
  gather_facts: no

  tasks:
      - name: Get Pools for F5 LTMs
        shell: "tmsh show running-config ltm pool one-line >> /tmp/pools1.txt"

- name: Connecting to localhost
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
      - name: Copy pools1.txt file from LTMs
        shell: "scp root@192.168.1.52:/tmp/pools1.txt /tmp/pools1.txt"
