- name: Connecting to DC1 LTMs
  hosts: dc1f5ltm01
  connection: ssh
  gather_facts: false
  environment:
    F5_PASSWORD: "Labrat@123"
    F5_USER: "admin"
    F5_SERVER: "192.168.1.52"

  tasks:
  
#   - name: Include vars of stuff.yml into the 'stuff' variable (2.2).
#     include_vars:
#      file: stuff.yml
#      name: stuff

   - name: Saving LTM config
     bigip_config:
      save: yes
      validate_certs: "no"
     delegate_to: localhost
     register: saveconfig
   
   - name: Syncing LTM config
     bigip_command:
      commands: "run /cm config-sync to-group Syncfailover"
      validate_certs: "no"
     delegate_to: localhost
     register: syncconfig

   - name: Creating nodes
     bigip_command:
      commands:
         - 'create ltm node 1.1.1.1 { address 1.1.1.1 }'
         - 'create ltm node 1.1.1.2 { address 1.1.1.2 }'
      validate_certs: "no"
     delegate_to: localhost
     register: nodes

   - name: Creating pool
     bigip_command:
      commands:
         - 'create ltm pool testpool-80 members add { 1.1.1.1:http { address 1.1.1.1 } 1.1.1.2:http { address 1.1.1.2 }}'
      validate_certs: "no"
     delegate_to: localhost
     register: pool

   - name: Creating virtual server
     bigip_command:
      commands:
         - 'create ltm virtual testvip-80 { destination 64.25.36.70:http ip-protocol tcp mask 255.255.255.255 pool testpool-80 profiles add { tcp { } } source 0.0.0.0/0 source-address-translation { type automap } }'
      validate_certs: "no"
     delegate_to: localhost
     register: virtual

   - name: Saving LTM config
     bigip_config:
      save: yes
      validate_certs: "no"
     delegate_to: localhost
     register: saveconfig
   
   - name: Syncing LTM config
     bigip_command:
      commands: "run /cm config-sync to-group Syncfailover"
      validate_certs: "no"
     delegate_to: localhost
     register: syncconfig

   - name: Post implementation testing
     bigip_command:
      commands:
         - 'list ltm virtual testvip-80 one-line'
         - 'list ltm pool testpool-80 one-line'
      validate_certs: "no"
     delegate_to: localhost
     register: posttest

   - debug:
      var: posttest.stdout
      #var: posttest.failed_conditions
   - name: Saving LTM output to a file
     local_action: copy content="{{ posttest.stdout }}" dest="/tmp/posttest.txt"


#      - name: Running pre test commands
#        remote_user: root
#        shell: "tmsh list ltm virtual one-line | grep site1"
#        #shell: "tmsh list ltm pool one-line | grep site1" 
#        register: pretest
#
#      - name: Saving LTM output to a file in /tmp/
#        local_action: copy content=""{{ pretest.stdout }}"" dest="/tmp/pretest.txt"

